apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
  namespace: streaming
data:
  NODE_ENV: "production"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CLIENT_URLS: "http://k8s-streamingapp-13c6fd7ed0-1760791278.us-east-1.elb.amazonaws.com"
  STREAMING_PUBLIC_URL: "http://k8s-streamingapp-13c6fd7ed0-1760791278.us-east-1.elb.amazonaws.com"
  AWS_CDN_URL: ""
