global:
  repositoryPrefix: "316412036553.dkr.ecr.us-east-1.amazonaws.com"
  tag: "initial"

namespace: production

services:
  frontend:
    port: 80
    containerPort: 80
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"

  auth:
    port: 3001
    replicas: 2
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  streaming:
    port: 3002
    replicas: 2
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1024Mi"

  admin:
    port: 3003
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"

  chat:
    port: 3004
    replicas: 2
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

deployment:

ingress:
  enabled: true
  host: "api.yourdomain.com" # Replace with your domain name
