apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamingapp-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/streamingapp-gitops.git' # Replace with GitOps Repo URL
    targetRevision: HEAD
    path: helm/streamingapp
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
