apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamingapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/SakarayAnilKumar/streamingapp-gitops'
    targetRevision: HEAD
    path: helm/streamingapp
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: streaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
